# Uncomment the next line to define a global platform for your project
# platform :ios, '18.4'

target 'Masonry Demo4' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
  # Pods for Masonry Demo4
end
